export const ITEMS_LOADING = "ITEMS_LOADING";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const UPDATETAGS_SUCCESS = "UPDATETAGS_SUCCESS";
export const UPDATETAGS_FAIL = "UPDATETAGS_FAIL";
export const UPDATEUSER_SUCCESS = "UPDATEUSER_SUCCESS";
export const UPDATEUSER_FAIL = "UPDATEUSER_FAIL";
export const EXPLORE_SUCCESS = "EXPLORE_SUCCESS";
export const EXPLORE_FAIL = "EXPLORE_FAIL";
export const MESSAGESEND_SUCCESS = "MESSAGESEND_SUCCESS";
export const MESSAGESEND_FAIL = "MESSAGESEND_FAIL";
<<<<<<< HEAD
export const MESSAGEUPDATE_SUCCESS = "MESSAGEUPDATE_SUCCESS";
export const MESSAGEUPDATE_FAIL = "MESSAGEUPDATE_FAIL";
=======
export const UPDATEFAMERATE_SUCCESS = "UPDATEFAMERATE_SUCCESS";
export const UPDATEFAMERATE_FAIL = "UPDATEFAMERATE_FAIL";
>>>>>>> e805d15b7d43d476a0ae3a80a98f201710616051
